name: Build

on:
  push:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use MSBuild (Windows)
      uses: microsoft/setup-msbuild@v1.0.0
      if: matrix.os == 'windows-latest'

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.8'

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64

    - shell: msys2 {0}
      run: |
        pacman --noconfirm -Suy
        export MSYS2_ARCH="x86_64"
        pacman --noconfirm -S --needed \
            base-devel \
            mingw-w64-$MSYS2_ARCH-gobject-introspection \
            mingw-w64-$MSYS2_ARCH-harfbuzz \
            mingw-w64-$MSYS2_ARCH-fontconfig \
            mingw-w64-$MSYS2_ARCH-fribidi \
            mingw-w64-$MSYS2_ARCH-libthai \
            mingw-w64-$MSYS2_ARCH-cairo \
            mingw-w64-$MSYS2_ARCH-meson \
            mingw-w64-$MSYS2_ARCH-toolchain \
            mingw-w64-$MSYS2_ARCH-cantarell-fonts
        
        cp /MINGW64/bin/* "subproject"

    - name: Build Pango
      run: |
        $env:PATH = "$PWD\subproject;$env:PATH"
        pip install requests
        python setup-build-pango.py

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: build/pango/pangobin/*
